FROM php:8.3-apache

# Enable Apache mod_rewrite
RUN a2enmod rewrite

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    wget \
    less \
    libmagickwand-dev \
    git
RUN docker-php-ext-install gd mysqli pdo pdo_mysql zip
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Putting PHP in prod mode
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Updating various values for a more working setup
RUN sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 20M/' $PHP_INI_DIR/php.ini
RUN sed -i 's/post_max_size = .*/post_max_size = 20M/' /usr/local/etc/php/php.ini
RUN sed -i 's/memory_limit = .*/memory_limit = 2048M/' /usr/local/etc/php/php.ini
RUN sed -i 's/max_execution_time = .*/max_execution_time = 300/' /usr/local/etc/php/php.ini
RUN sed -i 's/max_input_time = .*/max_input_time = 300/' /usr/local/etc/php/php.ini

# Bypass an upload bug
RUN echo 'LimitRequestBody 20971520' > /etc/apache2/conf-available/upload-size.conf
RUN a2enconf upload-size

RUN a2enmod headers



# Installing composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN mv composer.phar /usr/local/bin/composer

# Installing Laravel installer and making it global
RUN composer global require laravel/installer
RUN PATH="${PATH}:/root/.config/composer/vendor/bin"

RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|' /etc/apache2/sites-available/000-default.conf
RUN sed -i 's|<Directory /var/www/>|<Directory /var/www/html/public/>|' /etc/apache2/apache2.conf
RUN sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
