FROM php:8.3-apache

# Enable Apache mod_rewrite
RUN a2enmod rewrite

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    wget \
    less \
    libmagickwand-dev
RUN pecl install imagick
RUN docker-php-ext-enable imagick
#RUN pecl install imagick
RUN docker-php-ext-install gd mysqli pdo pdo_mysql zip
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
#RUN install-php-extensions imagick/imagick@master
# Install any additional PHP extensions if needed

# Installing wp-cli and making it global
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

# Putting PHP in prod mode
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Updating various values for a more working setup
RUN sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 20M/' $PHP_INI_DIR/php.ini
RUN sed -i 's/post_max_size = .*/post_max_size = 20M/' /usr/local/etc/php/php.ini
RUN sed -i 's/memory_limit = .*/memory_limit = 2048M/' /usr/local/etc/php/php.ini
RUN sed -i 's/max_execution_time = .*/max_execution_time = 300/' /usr/local/etc/php/php.ini
RUN sed -i 's/max_input_time = .*/max_input_time = 300/' /usr/local/etc/php/php.ini

# Bypass a bug stopping to upload any media to WP
RUN echo 'LimitRequestBody 20971520' > /etc/apache2/conf-available/upload-size.conf
RUN a2enconf upload-size

RUN a2enmod headers


